# Generated by Django 5.0.7 on 2024-09-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0002_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'پذیرش'), ('pending', 'در حال بررسی'), ('not accept', 'رد شده'), ('cancel', 'لغو شده')], max_length=16),
        ),
    ]
