# Generated by Django 5.0.7 on 2024-09-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0004_remove_reservationrequest_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='serve.place'),
            preserve_default=False,
        ),
    ]
