# Generated by Django 4.2.16 on 2024-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0005_reservationrequest_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'پذیرش'), ('pending', 'در حال بررسی'), ('not accept', 'رد'), ('cancel', 'لغو شده')], max_length=16),
        ),
    ]
