# Generated by Django 4.2.16 on 2024-09-28 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serve', '0007_alter_reservationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serve.place', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
