# Generated by Django 5.0.7 on 2024-08-12 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('09\\d{9}')], verbose_name='نام کاربری')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_staff', models.BooleanField(default=False, verbose_name='اجازه ورود')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_sets', related_query_name='user', to='auth.group', verbose_name='گروه')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_sets', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
                'ordering': ('name',),
            },
        ),
    ]
