# Generated by Django 5.0.7 on 2024-08-21 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=11, unique=True, validators=[django.core.validators.RegexValidator('09\\d{9}')], verbose_name='نام کاربری'),
        ),
    ]
