# Generated by Django 5.0.7 on 2024-08-29 13:59

import accounts.utils
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('09\\d{9}')], verbose_name='phone number')),
                ('tmp_code', models.CharField(default=accounts.utils.password_generator, max_length=6)),
                ('tmp_code_expire', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmp_code_sent_time', models.DateTimeField(default=accounts.utils.five_minute_ago)),
                ('tmp_code_sent_counter_in_last_24_hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SMSBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('09\\d{9}')], verbose_name='phone number')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
