# Generated by Django 4.2.16 on 2024-09-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phonecode_smsblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
